name: Main
version: ${project.version}
main: me.paradis.main.Main
api-version: 1.16
authors: [ Paradis ]
description: a bed plugin for Toxic
commands:
  beds:
    description: "adds a default respawn location to send the players when they close the GUI"
    usage: /beds [add/remove/player]